# encoding: utf-8

require 'test_helper'


class EntryTest < ActiveSupport::TestCase
  
  data("回答一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/panels/3810/answers -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連の作成　(公開設定から)", ["200", `curl -X POST http://localhost:9292/api/v1/collectors/2765/collector_segment_chains -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連の作成　(セグメント設定から)", ["200", `curl -X POST http://localhost:9292/api/v1/segments/572/collector_segment_chains -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/collector_segment_chains/429 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連一覧の取得　(公開設定から)", ["200", `curl -X GET http://localhost:9292/api/v1/collectors/2776/collector_segment_chains -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連一覧の取得　(セグメント設定から)", ["200", `curl -X GET http://localhost:9292/api/v1/segments/573/collector_segment_chains -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連の取得", ["200", `curl -X GET http://localhost:9292/api/v1/collector_segment_chains/430 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/collector_segment_chains/431 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定の公開中止", ["200", `curl -X POST http://localhost:9292/api/v1/collectors/2789/abort -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定の作成", ["200", `curl -X POST http://localhost:9292/api/v1/surveys/2251/collectors -d "auth_token=sxHNTa6w2hNxfzq7dHQo&collector[name]=new_collector" -w "%{http_code}"`])
  data("公開設定の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/collectors/2792 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys/2253/collectors -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定の公開", ["200", `curl -X POST http://localhost:9292/api/v1/collectors/2795/publish -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定の取得", ["200", `curl -X GET http://localhost:9292/api/v1/collectors/2797 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/collectors/2799 -d "auth_token=sxHNTa6w2hNxfzq7dHQo&collector[name]=new_collector" -w "%{http_code}"`])
  data("画像の作成", ["200", `curl -X POST http://localhost:9292/api/v1/surveys/2257/creatives -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("画像の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/creatives/1071 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("画像一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys/2259/creatives -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("画像の取得", ["200", `curl -X GET http://localhost:9292/api/v1/creatives/1072 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("画像の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/creatives/1073 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("デザインの取得", ["200", `curl -X GET http://localhost:9292/api/v1/designs/1 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("デザインの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/designs/1 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("最終画面の取得", ["200", `curl -X GET http://localhost:9292/api/v1/egressions/1 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("最終画面の変更", ["200", `curl -X PUT http://localhost:9292/api/v1/egressions/1 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("和文フォント一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/fonts -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("欧文フォント一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/google_fonts -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アクションの作成", ["200", `curl -X POST http://localhost:9292/api/v1/logics/483/logic_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アクションの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/logic_actions/413 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アクションの取得", ["200", `curl -X GET http://localhost:9292/api/v1/logic_actions/414 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アクションの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/logic_actions/415 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アイテムの作成", ["200", `curl -X POST http://localhost:9292/api/v1/logics/487/logic_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アイテムの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/logic_items/416 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アイテム一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/logics/489/logic_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アイテムの取得", ["200", `curl -X GET http://localhost:9292/api/v1/logic_items/417 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アイテムの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/logic_items/418 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐設定の作成", ["200", `curl -X POST http://localhost:9292/api/v1/questions/2666/logics -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐設定の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/logics/492 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐設定一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questions/2668/logics -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐設定の取得", ["200", `curl -X GET http://localhost:9292/api/v1/logics/493 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐設定の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/logics/494 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問順序一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questionnaires/1/page_order_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問順序の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/page_order_items/13 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答者一覧の取得(セグメント毎)", ["200", `curl -X GET http://localhost:9292/api/v1/segments/574/panels -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答者一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys/2271/panels -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答者の取得", ["200", `curl -X GET http://localhost:9292/api/v1/panels/3810 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("置き換え変数設定の作成", ["200", `curl -X POST http://localhost:9292/api/v1/questionnaires/1/questionnaire_variables -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("置き換え変数設定の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/questionnaire_variables/401 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("置き換え変数設定一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questionnaires/1/questionnaire_variables -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("置き換え変数設定の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questionnaire_variables/402 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("置き換え変数設定の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/questionnaire_variables/403 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問表一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys/2274/questionnaires -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問表の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questionnaires/1 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問の作成", ["200", `curl -X POST http://localhost:9292/api/v1/questionnaires/1/questions -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/questions/2671 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questionnaires/1/questions -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questions/2672 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/questions/2673 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("ランダム設定の作成", ["200", `curl -X POST http://localhost:9292/api/v1/questionnaires/1/randomizers -d "auth_token=sxHNTa6w2hNxfzq7dHQo&randomizer[step_num]=1&randomizer[start_index]=0&randomizer[end_index]=1" -w "%{http_code}"`])
  data("ランダム設定の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/randomizers/304 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("ランダム設定一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questionnaires/1/randomizers -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("ランダム設定の取得", ["200", `curl -X GET http://localhost:9292/api/v1/randomizers/305 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("ランダム設定の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/randomizers/306 -d "auth_token=sxHNTa6w2hNxfzq7dHQo&randomizer[step_num]=1&randomizer[start_index]=0&randomizer[end_index]=1" -w "%{http_code}"`])
  data("フィルターの作成", ["200", `curl -X POST http://localhost:9292/api/v1/segments/575/segment_filters -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("フィルターの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/segment_filters/278 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("フィルター一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/segments/577/segment_filters -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("フィルターの取得", ["200", `curl -X GET http://localhost:9292/api/v1/segment_filters/279 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("フィルターの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/segment_filters/280 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("セグメント設定の作成", ["200", `curl -X POST http://localhost:9292/api/v1/surveys/2294/segments -d "auth_token=sxHNTa6w2hNxfzq7dHQo&segment[name]=new_segment" -w "%{http_code}"`])
  data("セグメント設定の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/segments/580 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("セグメント設定一覧を取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys/2296/segments -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("セグメント設定の取得", ["200", `curl -X GET http://localhost:9292/api/v1/segments/581 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("セグメント設定の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/segments/582 -d "auth_token=sxHNTa6w2hNxfzq7dHQo&segment[name]=new_segment" -w "%{http_code}"`])
  data("回答補助項目の作成", ["200", `curl -X POST http://localhost:9292/api/v1/questions/2674/sub_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答補助項目の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/sub_items/4424 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答補助項目一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questions/2676/sub_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答補助項目の取得", ["200", `curl -X GET http://localhost:9292/api/v1/sub_items/4429 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答補助項目の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/sub_items/4432 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("アンケートの作成", ["200", `curl -X POST http://localhost:9292/api/v1/surveys -d "auth_token=sxHNTa6w2hNxfzq7dHQo&survey[name]=new_survey" -w "%{http_code}"`])
  data("アンケートの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/surveys/2301 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("アンケート一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("アンケートの取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys/2302 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("アンケートの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/surveys/2303 -d "auth_token=sxHNTa6w2hNxfzq7dHQo&survey[name]=new_survey" -w "%{http_code}"`])
  data("テーマ一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/themes -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ロジックの作成", ["200", `curl -X POST http://localhost:9292/api/v1/questions/2679/visibilities -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ロジックの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/visibilities/360 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ロジック一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questions/2681/visibilities -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ロジックの取得", ["200", `curl -X GET http://localhost:9292/api/v1/visibilities/361 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ロジックの更新", ["200", `curl -X GET http://localhost:9292/api/v1/visibilities/362 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示アイテムの作成", ["200", `curl -X POST http://localhost:9292/api/v1/visibilities/363/visibility_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示アイテムの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/visibility_items/321 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示アイテム一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/visibilities/365/visibility_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示アイテムの取得", ["200", `curl -X GET http://localhost:9292/api/v1/visibility_items/322 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示アイテムの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/visibility_items/323 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ターゲットの作成", ["200", `curl -X POST http://localhost:9292/api/v1/visibilities/368/visibility_targets -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ターゲットの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/visibility_targets/596 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ターゲット一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/visibilities/370/visibility_targets -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ターゲットの取得", ["200", `curl -X GET http://localhost:9292/api/v1/visibility_targets/599 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ターゲットの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/visibility_targets/601 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  def test_response_code(data)
    expected, response = data
    assert_equal expected, response.match(/[0-9]{3}$/).to_s, "#{response}"
  end
end
