# encoding: utf-8

require 'test_helper'


class EntryTest < ActiveSupport::TestCase
  
  data("回答項目の作成", ["200", `curl -X POST http://localhost:9292/api/v1/questions/3186/answer_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答項目の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/answer_items/6141 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答項目一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questions/3188/answer_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答項目の取得", ["200", `curl -X GET http://localhost:9292/api/v1/answer_items/6144 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答項目の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/answer_items/6146 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/panels/3810/answers -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連の作成　(公開設定から)", ["200", `curl -X POST http://localhost:9292/api/v1/collectors/5455/collector_segment_chains -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連の作成　(セグメント設定から)", ["200", `curl -X POST http://localhost:9292/api/v1/segments/667/collector_segment_chains -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/collector_segment_chains/465 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連一覧の取得　(公開設定から)", ["200", `curl -X GET http://localhost:9292/api/v1/collectors/5466/collector_segment_chains -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連一覧の取得　(セグメント設定から)", ["200", `curl -X GET http://localhost:9292/api/v1/segments/668/collector_segment_chains -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連の取得", ["200", `curl -X GET http://localhost:9292/api/v1/collector_segment_chains/466 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/collector_segment_chains/467 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定の公開中止", ["200", `curl -X POST http://localhost:9292/api/v1/collectors/5479/abort -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定の作成", ["200", `curl -X POST http://localhost:9292/api/v1/surveys/4853/collectors -d "auth_token=sxHNTa6w2hNxfzq7dHQo&collector[name]=new_collector" -w "%{http_code}"`])
  data("公開設定の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/collectors/5482 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys/4855/collectors -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定の公開", ["200", `curl -X POST http://localhost:9292/api/v1/collectors/5485/publish -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定の取得", ["200", `curl -X GET http://localhost:9292/api/v1/collectors/5487 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/collectors/5489 -d "auth_token=sxHNTa6w2hNxfzq7dHQo&collector[name]=new_collector" -w "%{http_code}"`])
  data("画像の関連一覧の取得(回答項目から)", ["200", `curl -X GET http://localhost:9292/api/v1/answer_items/6149/creative_chains -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("画像の関連一覧の取得(質問から)", ["200", `curl -X GET http://localhost:9292/api/v1/questions/3193/creative_chains -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("画像の関連一覧の取得(回答補助項目から)", ["200", `curl -X GET http://localhost:9292/api/v1/sub_items/5504/creative_chains -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("画像の関連の更新(回答項目から)", ["200", `curl -X PUT http://localhost:9292/api/v1/answer_items/creative_chains/9650 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("画像の関連の更新(質問から)", ["200", `curl -X PUT http://localhost:9292/api/v1/questions/creative_chains/9650 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("画像の関連の更新(回答補助項目から)", ["200", `curl -X PUT http://localhost:9292/api/v1/sub_items/creative_chains/9650 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("画像の作成", ["200", `curl -X POST http://localhost:9292/api/v1/surveys/4899/creatives -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("画像の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/creatives/1100 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("画像一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys/4901/creatives -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("画像の取得", ["200", `curl -X GET http://localhost:9292/api/v1/creatives/1101 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("画像の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/creatives/1102 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("デザインの取得", ["200", `curl -X GET http://localhost:9292/api/v1/designs/1 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("デザインの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/designs/1 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("最終画面の取得", ["200", `curl -X GET http://localhost:9292/api/v1/egressions/1 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("最終画面の変更", ["200", `curl -X PUT http://localhost:9292/api/v1/egressions/1 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("和文フォント一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/fonts -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("欧文フォント一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/google_fonts -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アクションの作成", ["200", `curl -X POST http://localhost:9292/api/v1/logics/576/logic_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アクションの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/logic_actions/472 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アクションの取得", ["200", `curl -X GET http://localhost:9292/api/v1/logic_actions/473 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アクションの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/logic_actions/474 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アイテムの作成", ["200", `curl -X POST http://localhost:9292/api/v1/logics/580/logic_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アイテムの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/logic_items/475 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アイテム一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/logics/582/logic_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アイテムの取得", ["200", `curl -X GET http://localhost:9292/api/v1/logic_items/476 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アイテムの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/logic_items/477 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐設定の作成", ["200", `curl -X POST http://localhost:9292/api/v1/questions/3219/logics -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐設定の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/logics/585 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐設定一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questions/3221/logics -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐設定の取得", ["200", `curl -X GET http://localhost:9292/api/v1/logics/586 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐設定の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/logics/587 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問順序一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questionnaires/1/page_order_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問順序の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/page_order_items/13 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答者一覧の取得(セグメント毎)", ["200", `curl -X GET http://localhost:9292/api/v1/segments/669/panels -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答者一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys/5005/panels -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答者の取得", ["200", `curl -X GET http://localhost:9292/api/v1/panels/3810 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("置き換え変数設定の作成", ["200", `curl -X POST http://localhost:9292/api/v1/questionnaires/1/questionnaire_variables -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("置き換え変数設定の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/questionnaire_variables/430 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("置き換え変数設定一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questionnaires/1/questionnaire_variables -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("置き換え変数設定の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questionnaire_variables/431 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("置き換え変数設定の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/questionnaire_variables/432 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問表一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys/5016/questionnaires -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問表の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questionnaires/1 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問の作成", ["200", `curl -X POST http://localhost:9292/api/v1/questionnaires/1/questions -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/questions/3224 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questionnaires/1/questions -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questions/3225 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/questions/3226 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("ランダム設定の作成", ["200", `curl -X POST http://localhost:9292/api/v1/questionnaires/1/randomizers -d "auth_token=sxHNTa6w2hNxfzq7dHQo&randomizer[step_num]=1&randomizer[start_index]=0&randomizer[end_index]=1" -w "%{http_code}"`])
  data("ランダム設定の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/randomizers/382 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("ランダム設定一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questionnaires/1/randomizers -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("ランダム設定の取得", ["200", `curl -X GET http://localhost:9292/api/v1/randomizers/383 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("ランダム設定の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/randomizers/384 -d "auth_token=sxHNTa6w2hNxfzq7dHQo&randomizer[step_num]=1&randomizer[start_index]=0&randomizer[end_index]=1" -w "%{http_code}"`])
  data("フィルターの作成", ["200", `curl -X POST http://localhost:9292/api/v1/segments/670/segment_filters -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("フィルターの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/segment_filters/307 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("フィルター一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/segments/672/segment_filters -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("フィルターの取得", ["200", `curl -X GET http://localhost:9292/api/v1/segment_filters/308 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("フィルターの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/segment_filters/309 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("セグメント設定の作成", ["200", `curl -X POST http://localhost:9292/api/v1/surveys/5052/segments -d "auth_token=sxHNTa6w2hNxfzq7dHQo&segment[name]=new_segment" -w "%{http_code}"`])
  data("セグメント設定の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/segments/675 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("セグメント設定一覧を取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys/5054/segments -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("セグメント設定の取得", ["200", `curl -X GET http://localhost:9292/api/v1/segments/676 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("セグメント設定の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/segments/677 -d "auth_token=sxHNTa6w2hNxfzq7dHQo&segment[name]=new_segment" -w "%{http_code}"`])
  data("回答補助項目の作成", ["200", `curl -X POST http://localhost:9292/api/v1/questions/3227/sub_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答補助項目の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/sub_items/5572 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答補助項目一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questions/3229/sub_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答補助項目の取得", ["200", `curl -X GET http://localhost:9292/api/v1/sub_items/5577 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答補助項目の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/sub_items/5580 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("アンケートの作成", ["200", `curl -X POST http://localhost:9292/api/v1/surveys -d "auth_token=sxHNTa6w2hNxfzq7dHQo&survey[name]=new_survey" -w "%{http_code}"`])
  data("アンケートの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/surveys/5077 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("アンケート一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("アンケートの取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys/5078 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("アンケートの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/surveys/5079 -d "auth_token=sxHNTa6w2hNxfzq7dHQo&survey[name]=new_survey" -w "%{http_code}"`])
  data("テーマ一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/themes -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ロジックの作成", ["200", `curl -X POST http://localhost:9292/api/v1/questions/3232/visibilities -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ロジックの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/visibilities/459 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ロジック一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questions/3234/visibilities -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ロジックの取得", ["200", `curl -X GET http://localhost:9292/api/v1/visibilities/460 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ロジックの更新", ["200", `curl -X GET http://localhost:9292/api/v1/visibilities/461 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示アイテムの作成", ["200", `curl -X POST http://localhost:9292/api/v1/visibilities/462/visibility_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示アイテムの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/visibility_items/350 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示アイテム一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/visibilities/464/visibility_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示アイテムの取得", ["200", `curl -X GET http://localhost:9292/api/v1/visibility_items/351 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示アイテムの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/visibility_items/352 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ターゲットの作成", ["200", `curl -X POST http://localhost:9292/api/v1/visibilities/467/visibility_targets -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ターゲットの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/visibility_targets/724 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ターゲット一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/visibilities/469/visibility_targets -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ターゲットの取得", ["200", `curl -X GET http://localhost:9292/api/v1/visibility_targets/727 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ターゲットの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/visibility_targets/729 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])

  def test_response_code(data)
    expected, response = data
    assert_equal expected, response.match(/[0-9]{3}$/).to_s, "#{response}"
  end

  def tear_down

  end
end
