# encoding: utf-8

require 'test_helper'


class EntryTest < ActiveSupport::TestCase
  
  data("回答一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/panels/3810/answers -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連の作成　(公開設定から)", ["200", `curl -X POST http://localhost:9292/api/v1/collectors/2573/collector_segment_chains -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連の作成　(セグメント設定から)", ["200", `curl -X POST http://localhost:9292/api/v1/segments/547/collector_segment_chains -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/collector_segment_chains/421 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連一覧の取得　(公開設定から)", ["200", `curl -X GET http://localhost:9292/api/v1/collectors/2584/collector_segment_chains -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連一覧の取得　(セグメント設定から)", ["200", `curl -X GET http://localhost:9292/api/v1/segments/548/collector_segment_chains -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連の取得", ["200", `curl -X GET http://localhost:9292/api/v1/collector_segment_chains/422 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定とセグメントの関連の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/collector_segment_chains/423 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定の公開中止", ["200", `curl -X POST http://localhost:9292/api/v1/collectors/2597/abort -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定の作成", ["200", `curl -X POST http://localhost:9292/api/v1/surveys/2080/collectors -d "auth_token=sxHNTa6w2hNxfzq7dHQo&collector[name]=new_collector" -w "%{http_code}"`])
  data("公開設定の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/collectors/2600 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys/2082/collectors -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定の公開", ["200", `curl -X POST http://localhost:9292/api/v1/collectors/2603/publish -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定の取得", ["200", `curl -X GET http://localhost:9292/api/v1/collectors/2605 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("公開設定の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/collectors/2607 -d "auth_token=sxHNTa6w2hNxfzq7dHQo&collector[name]=new_collector" -w "%{http_code}"`])
  data("画像の作成", ["200", `curl -X POST http://localhost:9292/api/v1/surveys/2086/creatives -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("画像の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/creatives/1064 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("画像一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys/2088/creatives -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("画像の取得", ["200", `curl -X GET http://localhost:9292/api/v1/creatives/1065 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("画像の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/creatives/1066 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("デザインの取得", ["200", `curl -X GET http://localhost:9292/api/v1/designs/1 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("デザインの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/designs/1 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("最終画面の取得", ["200", `curl -X GET http://localhost:9292/api/v1/egressions/1 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("最終画面の変更", ["200", `curl -X PUT http://localhost:9292/api/v1/egressions/1 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("和文フォント一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/fonts -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("欧文フォント一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/google_fonts -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アクションの作成", ["200", `curl -X POST http://localhost:9292/api/v1/logics/458/logic_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アクションの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/logic_actions/399 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アクションの取得", ["200", `curl -X GET http://localhost:9292/api/v1/logic_actions/400 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アクションの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/logic_actions/401 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アイテムの作成", ["200", `curl -X POST http://localhost:9292/api/v1/logics/462/logic_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アイテムの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/logic_items/402 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アイテム一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/logics/464/logic_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アイテムの取得", ["200", `curl -X GET http://localhost:9292/api/v1/logic_items/403 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐アイテムの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/logic_items/404 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐設定の作成", ["200", `curl -X POST http://localhost:9292/api/v1/questions/2549/logics -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐設定の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/logics/467 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐設定一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questions/2551/logics -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐設定の取得", ["200", `curl -X GET http://localhost:9292/api/v1/logics/468 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("分岐設定の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/logics/469 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問順序一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questionnaires/1/page_order_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問順序の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/page_order_items/13 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答者一覧の取得(セグメント毎)", ["200", `curl -X GET http://localhost:9292/api/v1/segments/549/panels -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答者一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys/2100/panels -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答者の取得", ["200", `curl -X GET http://localhost:9292/api/v1/panels/3810 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("置き換え変数設定の作成", ["200", `curl -X POST http://localhost:9292/api/v1/questionnaires/1/questionnaire_variables -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("置き換え変数設定の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/questionnaire_variables/394 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("置き換え変数設定一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questionnaires/1/questionnaire_variables -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("置き換え変数設定の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questionnaire_variables/395 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("置き換え変数設定の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/questionnaire_variables/396 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問表一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys/2103/questionnaires -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問表の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questionnaires/1 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問の作成", ["200", `curl -X POST http://localhost:9292/api/v1/questionnaires/1/questions -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/questions/2554 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questionnaires/1/questions -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questions/2555 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("質問の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/questions/2556 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("ランダム設定の作成", ["200", `curl -X POST http://localhost:9292/api/v1/questionnaires/1/randomizers -d "auth_token=sxHNTa6w2hNxfzq7dHQo&randomizer[step_num]=1" -w "%{http_code}"`])
  data("ランダム設定の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/randomizers/294 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("ランダム設定一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questionnaires/1/randomizers -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("ランダム設定の取得", ["200", `curl -X GET http://localhost:9292/api/v1/randomizers/295 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("ランダム設定の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/randomizers/296 -d "auth_token=sxHNTa6w2hNxfzq7dHQo&randomizer[step_num]=1" -w "%{http_code}"`])
  data("フィルターの作成", ["200", `curl -X POST http://localhost:9292/api/v1/segments/550/segment_filters -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("フィルターの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/segment_filters/271 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("フィルター一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/segments/552/segment_filters -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("フィルターの取得", ["200", `curl -X GET http://localhost:9292/api/v1/segment_filters/272 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("フィルターの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/segment_filters/273 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("セグメント設定の作成", ["200", `curl -X POST http://localhost:9292/api/v1/surveys/2123/segments -d "auth_token=sxHNTa6w2hNxfzq7dHQo&segment[name]=new_segment" -w "%{http_code}"`])
  data("セグメント設定の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/segments/555 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("セグメント設定一覧を取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys/2125/segments -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("セグメント設定の取得", ["200", `curl -X GET http://localhost:9292/api/v1/segments/556 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("セグメント設定の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/segments/557 -d "auth_token=sxHNTa6w2hNxfzq7dHQo&segment[name]=new_segment" -w "%{http_code}"`])
  data("回答補助項目の作成", ["200", `curl -X POST http://localhost:9292/api/v1/questions/2557/sub_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答補助項目の削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/sub_items/4191 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答補助項目一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questions/2559/sub_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答補助項目の取得", ["200", `curl -X GET http://localhost:9292/api/v1/sub_items/4196 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("回答補助項目の更新", ["200", `curl -X PUT http://localhost:9292/api/v1/sub_items/4199 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("アンケートの作成", ["200", `curl -X POST http://localhost:9292/api/v1/surveys -d "auth_token=sxHNTa6w2hNxfzq7dHQo&survey[name]=new_survey" -w "%{http_code}"`])
  data("アンケートの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/surveys/2130 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("アンケート一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("アンケートの取得", ["200", `curl -X GET http://localhost:9292/api/v1/surveys/2131 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("アンケートの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/surveys/2132 -d "auth_token=sxHNTa6w2hNxfzq7dHQo&survey[name]=new_survey" -w "%{http_code}"`])
  data("テーマ一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/themes -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ロジックの作成", ["200", `curl -X POST http://localhost:9292/api/v1/questions/2562/visibilities -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ロジックの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/visibilities/333 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ロジック一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/questions/2564/visibilities -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ロジックの取得", ["200", `curl -X GET http://localhost:9292/api/v1/visibilities/334 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ロジックの更新", ["200", `curl -X GET http://localhost:9292/api/v1/visibilities/335 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示アイテムの作成", ["200", `curl -X POST http://localhost:9292/api/v1/visibilities/336/visibility_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示アイテムの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/visibility_items/314 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示アイテム一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/visibilities/338/visibility_items -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示アイテムの取得", ["200", `curl -X GET http://localhost:9292/api/v1/visibility_items/315 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示アイテムの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/visibility_items/316 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ターゲットの作成", ["200", `curl -X POST http://localhost:9292/api/v1/visibilities/341/visibility_targets -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ターゲットの削除", ["200", `curl -X DELETE http://localhost:9292/api/v1/visibility_targets/562 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ターゲット一覧の取得", ["200", `curl -X GET http://localhost:9292/api/v1/visibilities/343/visibility_targets -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ターゲットの取得", ["200", `curl -X GET http://localhost:9292/api/v1/visibility_targets/565 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  data("表示ターゲットの更新", ["200", `curl -X PUT http://localhost:9292/api/v1/visibility_targets/567 -d "auth_token=sxHNTa6w2hNxfzq7dHQo" -w "%{http_code}"`])
  def test_response_code(data)
    expected, response = data
    assert_equal expected, response.match(/[0-9]{3}$/).to_s, "#{response}"
  end
end
